// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.2
// source: api/formula/v1/formula.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FormulaService_Validate_FullMethodName      = "/formula.FormulaService/Validate"
	FormulaService_Compile_FullMethodName       = "/formula.FormulaService/Compile"
	FormulaService_GetAST_FullMethodName        = "/formula.FormulaService/GetAST"
	FormulaService_ListFunctions_FullMethodName = "/formula.FormulaService/ListFunctions"
	FormulaService_GetFunction_FullMethodName   = "/formula.FormulaService/GetFunction"
)

// FormulaServiceClient is the client API for FormulaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FormulaServiceClient interface {
	Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error)
	Compile(ctx context.Context, in *CompileRequest, opts ...grpc.CallOption) (*CompileResponse, error)
	GetAST(ctx context.Context, in *GetASTRequest, opts ...grpc.CallOption) (*GetASTResponse, error)
	ListFunctions(ctx context.Context, in *ListFunctionsRequest, opts ...grpc.CallOption) (*ListFunctionsResponse, error)
	GetFunction(ctx context.Context, in *GetFunctionRequest, opts ...grpc.CallOption) (*GetFunctionResponse, error)
}

type formulaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFormulaServiceClient(cc grpc.ClientConnInterface) FormulaServiceClient {
	return &formulaServiceClient{cc}
}

func (c *formulaServiceClient) Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateResponse)
	err := c.cc.Invoke(ctx, FormulaService_Validate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *formulaServiceClient) Compile(ctx context.Context, in *CompileRequest, opts ...grpc.CallOption) (*CompileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompileResponse)
	err := c.cc.Invoke(ctx, FormulaService_Compile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *formulaServiceClient) GetAST(ctx context.Context, in *GetASTRequest, opts ...grpc.CallOption) (*GetASTResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetASTResponse)
	err := c.cc.Invoke(ctx, FormulaService_GetAST_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *formulaServiceClient) ListFunctions(ctx context.Context, in *ListFunctionsRequest, opts ...grpc.CallOption) (*ListFunctionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFunctionsResponse)
	err := c.cc.Invoke(ctx, FormulaService_ListFunctions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *formulaServiceClient) GetFunction(ctx context.Context, in *GetFunctionRequest, opts ...grpc.CallOption) (*GetFunctionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFunctionResponse)
	err := c.cc.Invoke(ctx, FormulaService_GetFunction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FormulaServiceServer is the server API for FormulaService service.
// All implementations must embed UnimplementedFormulaServiceServer
// for forward compatibility.
type FormulaServiceServer interface {
	Validate(context.Context, *ValidateRequest) (*ValidateResponse, error)
	Compile(context.Context, *CompileRequest) (*CompileResponse, error)
	GetAST(context.Context, *GetASTRequest) (*GetASTResponse, error)
	ListFunctions(context.Context, *ListFunctionsRequest) (*ListFunctionsResponse, error)
	GetFunction(context.Context, *GetFunctionRequest) (*GetFunctionResponse, error)
	mustEmbedUnimplementedFormulaServiceServer()
}

// UnimplementedFormulaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFormulaServiceServer struct{}

func (UnimplementedFormulaServiceServer) Validate(context.Context, *ValidateRequest) (*ValidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Validate not implemented")
}
func (UnimplementedFormulaServiceServer) Compile(context.Context, *CompileRequest) (*CompileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Compile not implemented")
}
func (UnimplementedFormulaServiceServer) GetAST(context.Context, *GetASTRequest) (*GetASTResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAST not implemented")
}
func (UnimplementedFormulaServiceServer) ListFunctions(context.Context, *ListFunctionsRequest) (*ListFunctionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFunctions not implemented")
}
func (UnimplementedFormulaServiceServer) GetFunction(context.Context, *GetFunctionRequest) (*GetFunctionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFunction not implemented")
}
func (UnimplementedFormulaServiceServer) mustEmbedUnimplementedFormulaServiceServer() {}
func (UnimplementedFormulaServiceServer) testEmbeddedByValue()                        {}

// UnsafeFormulaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FormulaServiceServer will
// result in compilation errors.
type UnsafeFormulaServiceServer interface {
	mustEmbedUnimplementedFormulaServiceServer()
}

func RegisterFormulaServiceServer(s grpc.ServiceRegistrar, srv FormulaServiceServer) {
	// If the following call panics, it indicates UnimplementedFormulaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FormulaService_ServiceDesc, srv)
}

func _FormulaService_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormulaServiceServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FormulaService_Validate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FormulaServiceServer).Validate(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FormulaService_Compile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormulaServiceServer).Compile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FormulaService_Compile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FormulaServiceServer).Compile(ctx, req.(*CompileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FormulaService_GetAST_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetASTRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormulaServiceServer).GetAST(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FormulaService_GetAST_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FormulaServiceServer).GetAST(ctx, req.(*GetASTRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FormulaService_ListFunctions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFunctionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormulaServiceServer).ListFunctions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FormulaService_ListFunctions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FormulaServiceServer).ListFunctions(ctx, req.(*ListFunctionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FormulaService_GetFunction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFunctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormulaServiceServer).GetFunction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FormulaService_GetFunction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FormulaServiceServer).GetFunction(ctx, req.(*GetFunctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FormulaService_ServiceDesc is the grpc.ServiceDesc for FormulaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FormulaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "formula.FormulaService",
	HandlerType: (*FormulaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Validate",
			Handler:    _FormulaService_Validate_Handler,
		},
		{
			MethodName: "Compile",
			Handler:    _FormulaService_Compile_Handler,
		},
		{
			MethodName: "GetAST",
			Handler:    _FormulaService_GetAST_Handler,
		},
		{
			MethodName: "ListFunctions",
			Handler:    _FormulaService_ListFunctions_Handler,
		},
		{
			MethodName: "GetFunction",
			Handler:    _FormulaService_GetFunction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/formula/v1/formula.proto",
}
