// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/formula/v1/formula.proto

package pb

import (
	_ "github.com/agoXQ/QuantLab/api/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Formula       string                 `protobuf:"bytes,1,opt,name=formula,proto3" json:"formula,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_api_formula_v1_formula_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_formula_v1_formula_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_api_formula_v1_formula_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateRequest) GetFormula() string {
	if x != nil {
		return x.Formula
	}
	return ""
}

type ValidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_api_formula_v1_formula_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_formula_v1_formula_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_api_formula_v1_formula_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *ValidateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CompileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Formula       string                 `protobuf:"bytes,1,opt,name=formula,proto3" json:"formula,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompileRequest) Reset() {
	*x = CompileRequest{}
	mi := &file_api_formula_v1_formula_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileRequest) ProtoMessage() {}

func (x *CompileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_formula_v1_formula_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileRequest.ProtoReflect.Descriptor instead.
func (*CompileRequest) Descriptor() ([]byte, []int) {
	return file_api_formula_v1_formula_proto_rawDescGZIP(), []int{2}
}

func (x *CompileRequest) GetFormula() string {
	if x != nil {
		return x.Formula
	}
	return ""
}

type CompileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AstJson       string                 `protobuf:"bytes,1,opt,name=ast_json,json=astJson,proto3" json:"ast_json,omitempty"`
	PlanJson      string                 `protobuf:"bytes,2,opt,name=plan_json,json=planJson,proto3" json:"plan_json,omitempty"`
	Valid         bool                   `protobuf:"varint,3,opt,name=valid,proto3" json:"valid,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompileResponse) Reset() {
	*x = CompileResponse{}
	mi := &file_api_formula_v1_formula_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileResponse) ProtoMessage() {}

func (x *CompileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_formula_v1_formula_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileResponse.ProtoReflect.Descriptor instead.
func (*CompileResponse) Descriptor() ([]byte, []int) {
	return file_api_formula_v1_formula_proto_rawDescGZIP(), []int{3}
}

func (x *CompileResponse) GetAstJson() string {
	if x != nil {
		return x.AstJson
	}
	return ""
}

func (x *CompileResponse) GetPlanJson() string {
	if x != nil {
		return x.PlanJson
	}
	return ""
}

func (x *CompileResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *CompileResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *CompileResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetASTRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Formula       string                 `protobuf:"bytes,1,opt,name=formula,proto3" json:"formula,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetASTRequest) Reset() {
	*x = GetASTRequest{}
	mi := &file_api_formula_v1_formula_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetASTRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetASTRequest) ProtoMessage() {}

func (x *GetASTRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_formula_v1_formula_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetASTRequest.ProtoReflect.Descriptor instead.
func (*GetASTRequest) Descriptor() ([]byte, []int) {
	return file_api_formula_v1_formula_proto_rawDescGZIP(), []int{4}
}

func (x *GetASTRequest) GetFormula() string {
	if x != nil {
		return x.Formula
	}
	return ""
}

type GetASTResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AstJson       string                 `protobuf:"bytes,1,opt,name=ast_json,json=astJson,proto3" json:"ast_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetASTResponse) Reset() {
	*x = GetASTResponse{}
	mi := &file_api_formula_v1_formula_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetASTResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetASTResponse) ProtoMessage() {}

func (x *GetASTResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_formula_v1_formula_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetASTResponse.ProtoReflect.Descriptor instead.
func (*GetASTResponse) Descriptor() ([]byte, []int) {
	return file_api_formula_v1_formula_proto_rawDescGZIP(), []int{5}
}

func (x *GetASTResponse) GetAstJson() string {
	if x != nil {
		return x.AstJson
	}
	return ""
}

type FunctionDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	ReturnType    string                 `protobuf:"bytes,3,opt,name=return_type,json=returnType,proto3" json:"return_type,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Params        []*FunctionParam       `protobuf:"bytes,5,rep,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionDefinition) Reset() {
	*x = FunctionDefinition{}
	mi := &file_api_formula_v1_formula_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionDefinition) ProtoMessage() {}

func (x *FunctionDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_api_formula_v1_formula_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionDefinition.ProtoReflect.Descriptor instead.
func (*FunctionDefinition) Descriptor() ([]byte, []int) {
	return file_api_formula_v1_formula_proto_rawDescGZIP(), []int{6}
}

func (x *FunctionDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionDefinition) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *FunctionDefinition) GetReturnType() string {
	if x != nil {
		return x.ReturnType
	}
	return ""
}

func (x *FunctionDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FunctionDefinition) GetParams() []*FunctionParam {
	if x != nil {
		return x.Params
	}
	return nil
}

type FunctionParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ParamType     string                 `protobuf:"bytes,2,opt,name=param_type,json=paramType,proto3" json:"param_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionParam) Reset() {
	*x = FunctionParam{}
	mi := &file_api_formula_v1_formula_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionParam) ProtoMessage() {}

func (x *FunctionParam) ProtoReflect() protoreflect.Message {
	mi := &file_api_formula_v1_formula_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionParam.ProtoReflect.Descriptor instead.
func (*FunctionParam) Descriptor() ([]byte, []int) {
	return file_api_formula_v1_formula_proto_rawDescGZIP(), []int{7}
}

func (x *FunctionParam) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionParam) GetParamType() string {
	if x != nil {
		return x.ParamType
	}
	return ""
}

type ListFunctionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFunctionsRequest) Reset() {
	*x = ListFunctionsRequest{}
	mi := &file_api_formula_v1_formula_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFunctionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFunctionsRequest) ProtoMessage() {}

func (x *ListFunctionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_formula_v1_formula_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFunctionsRequest.ProtoReflect.Descriptor instead.
func (*ListFunctionsRequest) Descriptor() ([]byte, []int) {
	return file_api_formula_v1_formula_proto_rawDescGZIP(), []int{8}
}

type ListFunctionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Functions     []*FunctionDefinition  `protobuf:"bytes,1,rep,name=functions,proto3" json:"functions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFunctionsResponse) Reset() {
	*x = ListFunctionsResponse{}
	mi := &file_api_formula_v1_formula_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFunctionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFunctionsResponse) ProtoMessage() {}

func (x *ListFunctionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_formula_v1_formula_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFunctionsResponse.ProtoReflect.Descriptor instead.
func (*ListFunctionsResponse) Descriptor() ([]byte, []int) {
	return file_api_formula_v1_formula_proto_rawDescGZIP(), []int{9}
}

func (x *ListFunctionsResponse) GetFunctions() []*FunctionDefinition {
	if x != nil {
		return x.Functions
	}
	return nil
}

type GetFunctionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFunctionRequest) Reset() {
	*x = GetFunctionRequest{}
	mi := &file_api_formula_v1_formula_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFunctionRequest) ProtoMessage() {}

func (x *GetFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_formula_v1_formula_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFunctionRequest.ProtoReflect.Descriptor instead.
func (*GetFunctionRequest) Descriptor() ([]byte, []int) {
	return file_api_formula_v1_formula_proto_rawDescGZIP(), []int{10}
}

func (x *GetFunctionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetFunctionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Function      *FunctionDefinition    `protobuf:"bytes,1,opt,name=function,proto3" json:"function,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFunctionResponse) Reset() {
	*x = GetFunctionResponse{}
	mi := &file_api_formula_v1_formula_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFunctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFunctionResponse) ProtoMessage() {}

func (x *GetFunctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_formula_v1_formula_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFunctionResponse.ProtoReflect.Descriptor instead.
func (*GetFunctionResponse) Descriptor() ([]byte, []int) {
	return file_api_formula_v1_formula_proto_rawDescGZIP(), []int{11}
}

func (x *GetFunctionResponse) GetFunction() *FunctionDefinition {
	if x != nil {
		return x.Function
	}
	return nil
}

var File_api_formula_v1_formula_proto protoreflect.FileDescriptor

const file_api_formula_v1_formula_proto_rawDesc = "" +
	"\n" +
	"\x1capi/formula/v1/formula.proto\x12\aformula\x1a\x1aapi/common/v1/common.proto\"+\n" +
	"\x0fValidateRequest\x12\x18\n" +
	"\aformula\x18\x01 \x01(\tR\aformula\"]\n" +
	"\x10ValidateResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\x05R\terrorCode\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"*\n" +
	"\x0eCompileRequest\x12\x18\n" +
	"\aformula\x18\x01 \x01(\tR\aformula\"\x94\x01\n" +
	"\x0fCompileResponse\x12\x19\n" +
	"\bast_json\x18\x01 \x01(\tR\aastJson\x12\x1b\n" +
	"\tplan_json\x18\x02 \x01(\tR\bplanJson\x12\x14\n" +
	"\x05valid\x18\x03 \x01(\bR\x05valid\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\x05R\terrorCode\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\")\n" +
	"\rGetASTRequest\x12\x18\n" +
	"\aformula\x18\x01 \x01(\tR\aformula\"+\n" +
	"\x0eGetASTResponse\x12\x19\n" +
	"\bast_json\x18\x01 \x01(\tR\aastJson\"\xb7\x01\n" +
	"\x12FunctionDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x1f\n" +
	"\vreturn_type\x18\x03 \x01(\tR\n" +
	"returnType\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12.\n" +
	"\x06params\x18\x05 \x03(\v2\x16.formula.FunctionParamR\x06params\"B\n" +
	"\rFunctionParam\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"param_type\x18\x02 \x01(\tR\tparamType\"\x16\n" +
	"\x14ListFunctionsRequest\"R\n" +
	"\x15ListFunctionsResponse\x129\n" +
	"\tfunctions\x18\x01 \x03(\v2\x1b.formula.FunctionDefinitionR\tfunctions\"(\n" +
	"\x12GetFunctionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"N\n" +
	"\x13GetFunctionResponse\x127\n" +
	"\bfunction\x18\x01 \x01(\v2\x1b.formula.FunctionDefinitionR\bfunction2\xe4\x02\n" +
	"\x0eFormulaService\x12?\n" +
	"\bValidate\x12\x18.formula.ValidateRequest\x1a\x19.formula.ValidateResponse\x12<\n" +
	"\aCompile\x12\x17.formula.CompileRequest\x1a\x18.formula.CompileResponse\x129\n" +
	"\x06GetAST\x12\x16.formula.GetASTRequest\x1a\x17.formula.GetASTResponse\x12N\n" +
	"\rListFunctions\x12\x1d.formula.ListFunctionsRequest\x1a\x1e.formula.ListFunctionsResponse\x12H\n" +
	"\vGetFunction\x12\x1b.formula.GetFunctionRequest\x1a\x1c.formula.GetFunctionResponseB*Z(github.com/agoXQ/QuantLab/app/formula/pbb\x06proto3"

var (
	file_api_formula_v1_formula_proto_rawDescOnce sync.Once
	file_api_formula_v1_formula_proto_rawDescData []byte
)

func file_api_formula_v1_formula_proto_rawDescGZIP() []byte {
	file_api_formula_v1_formula_proto_rawDescOnce.Do(func() {
		file_api_formula_v1_formula_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_formula_v1_formula_proto_rawDesc), len(file_api_formula_v1_formula_proto_rawDesc)))
	})
	return file_api_formula_v1_formula_proto_rawDescData
}

var file_api_formula_v1_formula_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_formula_v1_formula_proto_goTypes = []any{
	(*ValidateRequest)(nil),       // 0: formula.ValidateRequest
	(*ValidateResponse)(nil),      // 1: formula.ValidateResponse
	(*CompileRequest)(nil),        // 2: formula.CompileRequest
	(*CompileResponse)(nil),       // 3: formula.CompileResponse
	(*GetASTRequest)(nil),         // 4: formula.GetASTRequest
	(*GetASTResponse)(nil),        // 5: formula.GetASTResponse
	(*FunctionDefinition)(nil),    // 6: formula.FunctionDefinition
	(*FunctionParam)(nil),         // 7: formula.FunctionParam
	(*ListFunctionsRequest)(nil),  // 8: formula.ListFunctionsRequest
	(*ListFunctionsResponse)(nil), // 9: formula.ListFunctionsResponse
	(*GetFunctionRequest)(nil),    // 10: formula.GetFunctionRequest
	(*GetFunctionResponse)(nil),   // 11: formula.GetFunctionResponse
}
var file_api_formula_v1_formula_proto_depIdxs = []int32{
	7,  // 0: formula.FunctionDefinition.params:type_name -> formula.FunctionParam
	6,  // 1: formula.ListFunctionsResponse.functions:type_name -> formula.FunctionDefinition
	6,  // 2: formula.GetFunctionResponse.function:type_name -> formula.FunctionDefinition
	0,  // 3: formula.FormulaService.Validate:input_type -> formula.ValidateRequest
	2,  // 4: formula.FormulaService.Compile:input_type -> formula.CompileRequest
	4,  // 5: formula.FormulaService.GetAST:input_type -> formula.GetASTRequest
	8,  // 6: formula.FormulaService.ListFunctions:input_type -> formula.ListFunctionsRequest
	10, // 7: formula.FormulaService.GetFunction:input_type -> formula.GetFunctionRequest
	1,  // 8: formula.FormulaService.Validate:output_type -> formula.ValidateResponse
	3,  // 9: formula.FormulaService.Compile:output_type -> formula.CompileResponse
	5,  // 10: formula.FormulaService.GetAST:output_type -> formula.GetASTResponse
	9,  // 11: formula.FormulaService.ListFunctions:output_type -> formula.ListFunctionsResponse
	11, // 12: formula.FormulaService.GetFunction:output_type -> formula.GetFunctionResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_formula_v1_formula_proto_init() }
func file_api_formula_v1_formula_proto_init() {
	if File_api_formula_v1_formula_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_formula_v1_formula_proto_rawDesc), len(file_api_formula_v1_formula_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_formula_v1_formula_proto_goTypes,
		DependencyIndexes: file_api_formula_v1_formula_proto_depIdxs,
		MessageInfos:      file_api_formula_v1_formula_proto_msgTypes,
	}.Build()
	File_api_formula_v1_formula_proto = out.File
	file_api_formula_v1_formula_proto_goTypes = nil
	file_api_formula_v1_formula_proto_depIdxs = nil
}
